import enum

class UserRole(str, enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    MANAGEMENT = "MANAGEMENT"
    MAINTENANCE_MANAGER = "MAINTENANCE_MANAGER"
    TECHNICIAN = "TECHNICIAN"
    WAREHOUSE = "WAREHOUSE"
    VIEWER = "VIEWER"

class MachineStatus(str, enum.Enum):
    OPERATIONAL = "OPERATIONAL"
    WARNING = "WARNING"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"
    DECOMMISSIONED = "DECOMMISSIONED"
    WAREHOUSE_BACKUP = "WAREHOUSE_BACKUP"

class DataQualityStatus(str, enum.Enum):
    VALID = "VALID"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INVALID = "INVALID"
    CORRECTED = "CORRECTED"

class TicketSource(str, enum.Enum):
    CUSTOMER_QR = "CUSTOMER_QR"
    WHATSAPP = "WHATSAPP"
    PHONE = "PHONE"
    MANUAL = "MANUAL"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    IMPORT = "IMPORT"

class TicketStatus(str, enum.Enum):
    NEW = "NEW"
    TRIAGED = "TRIAGED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_PART = "WAITING_FOR_PART"
    WAITING_FOR_CUSTOMER = "WAITING_FOR_CUSTOMER"
    RESOLVED = "RESOLVED"
    VERIFIED = "VERIFIED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

class TicketPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class FaultCategory(str, enum.Enum):
    PAYMENT = "PAYMENT"
    POS = "POS"
    CARD_READER = "CARD_READER"
    CASH_ACCEPTOR = "CASH_ACCEPTOR"
    PRODUCT_DISPENSING = "PRODUCT_DISPENSING"
    MOTOR = "MOTOR"
    SENSOR = "SENSOR"
    DISPLAY = "DISPLAY"
    TOUCH_SCREEN = "TOUCH_SCREEN"
    POWER = "POWER"
    NETWORK = "NETWORK"
    TEMPERATURE = "TEMPERATURE"
    REFRIGERATION = "REFRIGERATION"
    DOOR = "DOOR"
    COIN_SYSTEM = "COIN_SYSTEM"
    SOFTWARE = "SOFTWARE"
    MECHANICAL = "MECHANICAL"
    OTHER = "OTHER"

class TechnicianStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    BUSY = "BUSY"
    OFFLINE = "OFFLINE"
    ON_LEAVE = "ON_LEAVE"

class InventoryTransactionType(str, enum.Enum):
    RECEIVE = "RECEIVE"
    ISSUE = "ISSUE"
    RETURN = "RETURN"
    ADJUSTMENT = "ADJUSTMENT"
    TRANSFER = "TRANSFER"
    SCRAP = "SCRAP"

class PartRequestStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    ORDERED = "ORDERED"
    RECEIVED = "RECEIVED"
    ISSUED = "ISSUED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class NotificationType(str, enum.Enum):
    TICKET_CREATED = "TICKET_CREATED"
    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_ESCALATED = "TICKET_ESCALATED"
    LOW_STOCK_WARNING = "LOW_STOCK_WARNING"
    PART_REQUEST_PENDING = "PART_REQUEST_PENDING"
    SYSTEM_ALERT = "SYSTEM_ALERT"
